name: tutor_live
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  google_fonts: ^2.3.1
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.13
  bubble_tab_indicator: ^0.1.6
  intl: ^0.17.0
  http: ^0.13.4
  get_storage: ^2.0.3
  test: ^1.19.5
  mockito: ^5.1.0
  build_runner: ^2.1.10
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_native_splash: ^2.0.2
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0

flutter_native_splash:
  image: assets/images/logo.png
  color: "#fafafa"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
